### ISSUE TITLE
Adjust tow vehicle max speed based on vehicle chains

### ISSUE THREAD

**Issue by sethduda** [sethduda/AdvancedTowing#3]
Maybe...

adjusted speed = adjusted speed / 2 ^ ( number of towed vehicles - 1 )

e.g.

Towing 1 vehicle works as normal
Towing 2 vehicles is twice as slow as normal
Towing 3 vehicles is 4x as slow
Towing 4 vehicles is 8x as slow....

**Comment by ka0sCODE** [comment]
Make a toggable option whether you want to allow daisy trains or not, not everybody will love this because it's wildly unrealistic.

**Comment by sethduda** [comment]
This has been fixed in v1.2. By default, chaining is disabled. This can be enabled by setting the SA_TOW_CHAINS_ENABLED to true in your init.sqf file.
