### ISSUE TITLE
Exile 1.0.0 Get Deploy Tow Rope Option, but nothing happens.

### ISSUE THREAD

**Issue by RAW5niper** [sethduda/AdvancedTowing#30]
I get the Deploy Tow Rope Option but nothing happens.
1)I added the SA_AdvancedTowing.pbo to the @Exile_Server/addons
2)I added to the -servermod command line startup parameters, "@SA_AdvancedTowing;"
3)Since I use infiSTAR, I edited the CfgRemoteExec.hpp to inlcude:
class CfgRemoteExec
{
    class Functions
    {
        mode = 1;
        jip = 0;
        class fnc_AdminReq { allowedTargets=2; };
        class ExileServer_system_network_dispatchIncomingMessage { allowedTargets=2; };
        class SA_Simulate_Towing            { allowedTargets=0; }; 
        class SA_Attach_Tow_Ropes           { allowedTargets=0; }; 
        class SA_Take_Tow_Ropes             { allowedTargets=0; }; 
        class SA_Put_Away_Tow_Ropes         { allowedTargets=0; }; 
        class SA_Pickup_Tow_Ropes           { allowedTargets=0; }; 
        class SA_Drop_Tow_Ropes             { allowedTargets=0; }; 
        class SA_Set_Owner                  { allowedTargets=2; }; 
        class SA_Hint                       { allowedTargets=1; }; 
        class SA_Hide_Object_Global         { allowedTargets=2; }; 

```
};
class Commands
{
    mode=0;
    jip=0;
};
```

};

So, what am I missing/doing wrong?

Also, I put the SA_AdvancedTowing folder with the fn_advancedTowingInit.sqf functions file into the
addons folder in my mission folder. However, I'm uncertain how to call it from withing the initServer.sqf since there is already much code in there (I'm assuming for map objects for the traders).

**Comment by sethduda** [comment]
Can you check your client and server logs to see if any errors appear when
you press the deploy action? Something is blocking your network traffic.

**Comment by RAW5niper** [comment]
Thanks for the reply sethduda. I am not seeing any errors.
What are the correct installation instructions? I have read many different ideas online that left me confused. I'm trying to replace R3F with your Advanced Towing.
Should I be calling the script from the initServer.sqf? Like I mentioned in my original question?
I tried adding @AdvancedTowing mod to Arma Launcher, but then I get errors about keys.
Does this require players to have subscribed to this mod? And do they have to add the mod to the ARMA launcher? I was hoping, it would not need that. I know R3F had is down side, but I did like the fact that it did not require anyone to download, and or install anything additional to connect to the server.
I read online in the exile mod forum, that there were only two steps to this.
1) add the @SA_AdvancedTowing folder to the @Exile_Server addons folder, and add the "@AdvancedTowing;" to the command line. I questioned whether the proper command line would be @AdvancedTowing, or@SA_Advanced towing. Not sure. 
Also not sure why some other posts say to add it to the mission addons folder, and call something or other via the initServer.sqf file, yet others say players would have to download a mod or subscribe to it on steam before connecting.
Here is my post on Exile Mod site:
http://www.exilemod.com/topic/12914-releasedudaxld-adv-towing-for-exileupdated-4-16/?page=40#comment-110874

**Comment by sethduda** [comment]
You can find the official install directions on this github page.

Typical way of installing addons is to put the @ folder inside your arma 3
directory, and then change your server startup command line to use the mod
via the -serverMod command line option. (-serverMod is used for addons that
only the server needs. -mod is used for addons that the server + clients
need). Clients don't need this addon installed.

**Comment by RAW5niper** [comment]
Is the correct -serverMod command @AdvancedTowing, or @SA_AdvancedTowing?

**Comment by RAW5niper** [comment]
AH! Got it working. Not sure why there is much conflicting info online throughout.
Very simple if you download it from here:
https://github.com/sethduda/AdvancedTowing/releases

What are the towing requirements for helis? I tried towing with a mohawk, but didn't see
any deploy tow ropes option. Is there a place to add helis to tow?

Thanks again!

**Comment by sethduda** [comment]
Do you want to pick up the vehicle with the heli? If yes, you should use my
sling loading addon.

If you're trying to tow something with a heli, it will work, but the
vehicle can't be lifted off the ground. The ropes will snap. To do that,
there's an example in the github readme for changing which vehicles are
allowed to deploy tow ropes.

**Comment by RAW5niper** [comment]
Ok. I will look into the sling loading addons. :D

**Comment by sethduda** [comment]
https://github.com/sethduda/AdvancedSlingLoading

**Comment by RAW5niper** [comment]
Thanks.
Same installation? Didn't see an @AdvancedSlingLoading folder.
Should I create one? Just wondering, as all other mod folders start out with @.

**Comment by sethduda** [comment]
Yes - you can create one. Name doesn't really matter. As long as it matches
the name you put in the -serverMod command line arg.

On Thursday, July 14, 2016, RAW5niper notifications@github.com wrote:

> Thanks.
> Same installation? Didn't see an @AdvancedSlingLoading folder.
> Should I create one? Just wondering, as all other mod folders start out
> with @.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/sethduda/AdvancedTowing/issues/30#issuecomment-232777109,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOoBxnnvfDCZoIrttKtJN61w5w77Pvviks5qVpcSgaJpZM4JMqy_
> .

## 

Sent from my phone
