### ISSUE TITLE
Vehicles float when towed over water

### ISSUE THREAD

**Issue by sethduda** [sethduda/AdvancedTowing#4]
Only boats should float when towed over water

**Comment by sethduda** [comment]
Here's an example video:

https://www.youtube.com/watch?v=2yl9g7KHCD4&feature=youtu.be

**Comment by ka0sCODE** [comment]
You could make an identifier for surfaceType, 

_surface = surfaceType position player; <- Use that in debug console, to figure out the surfaces, and block the surface / detach vehicle on contact with surface to disallow.

**Comment by sethduda** [comment]
This has been fixed in v1.2
