### ISSUE TITLE
Disallow Safezone towing (Prevent ninja-jacking of vehicles)

### ISSUE THREAD

**Issue by ka0sCODE** [sethduda/AdvancedTowing#5]
Make checks for: 

`
if (ExilePlayerInSafezone)
if (!ExilePlayerInSafezone)
`

For disallowing towing in Safezones to prevent ninja-jacking, make it as a toggable option.

**Comment by sethduda** [comment]
Thanks - added to the latest source

**Comment by sethduda** [comment]
Released on steam in v1.2.1
